name: katkoot_elwady
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.15+23

environment:
  sdk: ">=2.19.0 < 4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.2
  firebase_app_check: ^0.3.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  dio: ^5.8.0+1
  easy_localization: ^3.0.1
  internet_connection_checker: ^3.0.1
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  pin_code_fields: ^8.0.1
  math_expressions: ^2.3.1
  onesignal_flutter: ^3.4.1
  sms_autofill: ^2.2.0
  shimmer: ^3.0.0
  google_maps_flutter: ^2.2.0
  url_launcher: ^6.1.5
  lottie: ^3.3.1
  flutter_xlider: ^3.5.0
  expandable: ^5.0.1
  location: ^8.0.0
  syncfusion_flutter_pdfviewer: ^28.2.4
  printing: ^5.9.3
  pdf: ^3.8.3
  http: ^1.3.0
  carousel_slider: ^5.0.0
  flutter_app_badger: ^1.4.0
  flick_video_player: ^0.9.0
  youtube_player_iframe: ^5.2.1
  convex_bottom_bar: ^3.0.0
  multi_select_flutter: ^4.1.2
  youtube_player_flutter: ^9.1.1
  chewie: ^1.3.5
  fl_chart: ^0.70.2
  youtube_explode_dart: ^2.3.9
  flutter_riverpod: ^2.4.9
  country_picker: ^2.0.16


dev_dependencies:
  flutter_test:
    sdk: flutter
#  expandable: ^5.0.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/
  #   - images/a_dot_ham.jpegtranslations

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Katkot_EL_Wadi_Icons
      fonts:
        - asset: assets/fonts/Katkot_EL_Wadi_Icons.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial.ttf
        - weight: 400
        - asset: assets/fonts/Arial-Bold.ttf
        - weight: 700

    - family: GE_SS_Two
      fonts:
        - asset: assets/fonts/GE_SS_Two_Medium.otf
        - weight: 400
        - asset: assets/fonts/GE-SS-Two-Bold.otf
        - weight: 700
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
